version: "3.5"

services:
  grafana8:
    image: grafana/grafana:latest
    network_mode: "bridge"
    container_name: grafana 
    # user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    # password admin : Admin123
    volumes:
      - /Users/atdmac1/Codes/docker-compose/grafana/data:/var/lib/grafana
    ports:
      - "12346:3000"
    restart: always